// database.js
const rptDatabase = [
    // --- 2m (VHF) REPETITORJI ---
    { klic: "S55VLM", lokacija: "Ljubljana Center", frekvenca: "145.575", ton: "77.0", vrsta: "2m", opomba: "DMR/FM mixmode" },
    { klic: "S55VLI", lokacija: "Lisca", frekvenca: "145.575", ton: "123.0", vrsta: "2m", opomba: "DMR, C4FM & FM" },
    { klic: "S55VCM", lokacija: "Malič", frekvenca: "145.5875", ton: "123.0", vrsta: "2m", opomba: "Celje, Laško" },
    { klic: "S55VKR", lokacija: "Mohor", frekvenca: "145.6125", ton: "ne", vrsta: "2m", opomba: "" },
    { klic: "S55VRT", lokacija: "Stucinov hrib", frekvenca: "145.6125", ton: "123.0", vrsta: "2m", opomba: "Rimske toplice" },
    { klic: "S55VKP", lokacija: "Nanos", frekvenca: "145.625", ton: "123.0", vrsta: "2m", opomba: "C4FM WIRES-X" },
    { klic: "S55VBO", lokacija: "Kobla", frekvenca: "145.6375", ton: "123.0", vrsta: "2m", opomba: "FM/DMR mixmode" },
    { klic: "S55VSC", lokacija: "Stare Slemene", frekvenca: "145.6375", ton: "77.0", vrsta: "2m", opomba: "Echolink" },
    { klic: "S55VNM", lokacija: "Trdinov vrh", frekvenca: "145.650", ton: "123.0 (TX)", vrsta: "2m", opomba: "" },
    { klic: "S55VBG", lokacija: "Kup", frekvenca: "145.650", ton: "ne", vrsta: "2m", opomba: "Podbrdo" },
    { klic: "S55VSG", lokacija: "Korada", frekvenca: "145.675", ton: "ne", vrsta: "2m", opomba: "" },
    { klic: "S55VRK", lokacija: "Uršlja gora", frekvenca: "145.675", ton: "ne", vrsta: "2m", opomba: "System Fusion" },
    { klic: "S55VKG", lokacija: "Sr. Vrh - Kr. Gora", frekvenca: "145.675", ton: "ne", vrsta: "2m", opomba: "" },
    { klic: "S55VZV", lokacija: "Žagarski vrh", frekvenca: "145.6875", ton: "77.0", vrsta: "2m", opomba: "" },
    { klic: "S55VCE", lokacija: "Mrzlica", frekvenca: "145.700", ton: "123.0", vrsta: "2m", opomba: "Hytera BM" },
    { klic: "S55VPO", lokacija: "Pečna reber", frekvenca: "145.7125", ton: "123.0", vrsta: "2m", opomba: "Postojna - DMR/FM" },
    { klic: "S55VID", lokacija: "Vojsko", frekvenca: "145.725", ton: "ne", vrsta: "2m", opomba: "System Fusion" },
    { klic: "S55VMB", lokacija: "Pohorje", frekvenca: "145.725", ton: "ne", vrsta: "2m", opomba: "Razgledni stolp" },
    { klic: "S55VJE", lokacija: "Jesenice", frekvenca: "145.725", ton: "ne", vrsta: "2m", opomba: "" },
    { klic: "S55VOR", lokacija: "Veliki Brebrovnik", frekvenca: "145.7375", ton: "123.0", vrsta: "2m", opomba: "Ormož - Wires-X" },
    { klic: "S55VIB", lokacija: "Grmada", frekvenca: "145.750", ton: "123.0", vrsta: "2m", opomba: "" },
    { klic: "S55VBR", lokacija: "Karlovica", frekvenca: "145.750", ton: "DTMF 7", vrsta: "2m", opomba: "" },
    { klic: "S55VIZ", lokacija: "Malija", frekvenca: "145.7625", ton: "123.0", vrsta: "2m", opomba: "Izola - Echolink" },
    { klic: "S55VLJ", lokacija: "Krim", frekvenca: "145.775", ton: "123.0", vrsta: "2m", opomba: "" },
    { klic: "S55VTO", lokacija: "Kanin", frekvenca: "145.7875", ton: "123.0", vrsta: "2m", opomba: "" },
    { klic: "S55VMO", lokacija: "Spodnje Kraše", frekvenca: "145.7875", ton: "ne", vrsta: "2m", opomba: "Mozirje" },
    { klic: "S55VKK", lokacija: "Čretež", frekvenca: "145.7875", ton: "123.0", vrsta: "2m", opomba: "Krško" },

    // --- 70cm (UHF) REPETITORJI ---
    { klic: "S55UBK", lokacija: "Mirna gora", frekvenca: "438.600", ton: "ne", vrsta: "70cm", opomba: "Crossband 2m" },
    { klic: "S55USC", lokacija: "Stare Slemene", frekvenca: "438.625", ton: "123.0", vrsta: "70cm", opomba: "Echolink" },
    { klic: "S55UKV", lokacija: "Krvavec", frekvenca: "438.675", ton: "123.0", vrsta: "70cm", opomba: "Echolink SLO" },
    { klic: "S55UKP", lokacija: "Nanos", frekvenca: "438.700", ton: "123.0", vrsta: "70cm", opomba: "Test" },
    { klic: "S55UBR", lokacija: "Brežice", frekvenca: "438.725", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55UTB", lokacija: "Zg. Kocjan", frekvenca: "438.725", ton: "123.0", vrsta: "70cm", opomba: "Radenci - Multimode" },
    { klic: "S55UGO", lokacija: "Trstelj", frekvenca: "438.750", ton: "123.0", vrsta: "70cm", opomba: "Multimode" },
    { klic: "S55ULX", lokacija: "Krim", frekvenca: "438.775", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55UPI", lokacija: "RK Piran", frekvenca: "438.800", ton: "ne", vrsta: "70cm", opomba: "DMR/FM" },
    { klic: "S55UBC", lokacija: "Boč", frekvenca: "438.825", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55UPO", lokacija: "Pečna reber", frekvenca: "438.825", ton: "123.0", vrsta: "70cm", opomba: "Echolink" },
    { klic: "S55ULJ", lokacija: "Janče", frekvenca: "438.875", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55USG", lokacija: "Korada", frekvenca: "438.875", ton: "ne", vrsta: "70cm", opomba: "" },
    { klic: "S55USX", lokacija: "Sv. Rok", frekvenca: "438.900", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55UCE", lokacija: "Celje Trnovlje", frekvenca: "438.950", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55USE", lokacija: "Laze", frekvenca: "439.000", ton: "123.0", vrsta: "70cm", opomba: "Sevnica - Echolink" },
    { klic: "S55UBO", lokacija: "Kobla", frekvenca: "439.025", ton: "123.0", vrsta: "70cm", opomba: "FM/DMR" },
    { klic: "S55DMR", lokacija: "Lisca", frekvenca: "439.075", ton: "123.0", vrsta: "70cm", opomba: "FM/DMR" },
    { klic: "S55UHF", lokacija: "Kum", frekvenca: "439.125", ton: "123.0", vrsta: "70cm", opomba: "SVXLink" },
    { klic: "S55UKO", lokacija: "Mala Kopa", frekvenca: "439.150", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55DTR", lokacija: "Sv. Planina", frekvenca: "439.175", ton: "123.0", vrsta: "70cm", opomba: "Trbovlje - FM/DMR" },
    { klic: "S55UKK", lokacija: "Čretež", frekvenca: "439.200", ton: "123.0", vrsta: "70cm", opomba: "Krško - Echolink" },
    { klic: "S55UMX", lokacija: "Pohorje MB", frekvenca: "439.200", ton: "88.5", vrsta: "70cm", opomba: "Maribor" },
    { klic: "S55UMB", lokacija: "Pohorje stolp", frekvenca: "439.225", ton: "ne", vrsta: "70cm", opomba: "" },
    { klic: "S55UID", lokacija: "Vojsko", frekvenca: "439.225", ton: "ne", vrsta: "70cm", opomba: "" },
    { klic: "S55UVL", lokacija: "Zgonce", frekvenca: "439.250", ton: "77.0", vrsta: "70cm", opomba: "Velike Lašče" },
    { klic: "S55UZA", lokacija: "Mrzlica", frekvenca: "439.275", ton: "123.0", vrsta: "70cm", opomba: "SVX Link" },
    { klic: "S55UCM", lokacija: "Malič", frekvenca: "439.300", ton: "123.0", vrsta: "70cm", opomba: "Echolink" },
    { klic: "S55URS", lokacija: "Strmec", frekvenca: "439.325", ton: "91.5", vrsta: "70cm", opomba: "Rogaška Slatina" },
    { klic: "S55UJE", lokacija: "Struška", frekvenca: "439.325", ton: "ne", vrsta: "70cm", opomba: "Solar" },
    { klic: "S55UAR", lokacija: "Stol", frekvenca: "439.3625", ton: "123.0", vrsta: "70cm", opomba: "" },
    { klic: "S55URK", lokacija: "Uršlja gora", frekvenca: "439.375", ton: "ne", vrsta: "70cm", opomba: "DMR BM" },
    { klic: "S55DAR", lokacija: "Stol", frekvenca: "439.400", ton: "123.0", vrsta: "70cm", opomba: "DMR/FM BM" }
];

 const dxcc = [
            { p: "A2", c: "Botswana", cq: "38", itu: "57" },
{ p: "A3", c: "Tonga Isl.", cq: "32", itu: "62" },
{ p: "A4", c: "Oman & Muscat", cq: "21", itu: "39" },
{ p: "A5", c: "Bhutan", cq: "22", itu: "41" },
{ p: "A6", c: "United Arab Emirates", cq: "21", itu: "39" },
{ p: "A7", c: "Qatar", cq: "21", itu: "39" },
{ p: "A9", c: "Bahrain", cq: "21", itu: "39" },
{ p: "AP", c: "Pakistan", cq: "21", itu: "41" },
{ p: "BS7", c: "Scarborough Reef", cq: "27", itu: "50" },
{ p: "BV", c: "Taiwan", cq: "24", itu: "44" },
{ p: "BV9P", c: "Pratas", cq: "24", itu: "44" },
{ p: "BX-BZ", c: "China", cq: "23,24", itu: "42,43,44" },
{ p: "C2", c: "Rep. of Nauru", cq: "31", itu: "65" },
{ p: "C3", c: "Andorra", cq: "14", itu: "27" },
{ p: "C5", c: "Gambia", cq: "35", itu: "46" },
{ p: "C6", c: "Bahamas", cq: "08", itu: "11" },
{ p: "C9", c: "Mozambique", cq: "37", itu: "53" },
{ p: "CE", c: "Chile", cq: "12", itu: "14,15,16" },
{ p: "CE9, KC4", c: "Antarctica", cq: "13", itu: "73" },
{ p: "CE0", c: "Easter Isl.", cq: "12", itu: "63" },
{ p: "CE0", c: "San Felix Isl.", cq: "12", itu: "14" },
{ p: "CE0", c: "Juan Fernandez Isl.", cq: "12", itu: "14" },
{ p: "CM, CO", c: "Cuba", cq: "08", itu: "11" },
{ p: "CN", c: "Morocco", cq: "33", itu: "37" },
{ p: "CP", c: "Bolivia", cq: "12", itu: "12,13,14" },
{ p: "CT", c: "Portugal", cq: "14", itu: "37" },
{ p: "CT3", c: "Madeira Isl.", cq: "33", itu: "36" },
{ p: "CU", c: "Azores Isl.", cq: "14", itu: "36" },
{ p: "CV-CX", c: "Uruguay", cq: "13", itu: "14" },
{ p: "CY0", c: "Sable Isl.", cq: "05", itu: "09" },
{ p: "CY9", c: "St. Paul Isl.", cq: "05", itu: "09" },
{ p: "D2, D3", c: "Angola", cq: "36", itu: "52" },
{ p: "D4", c: "Rep. of Cape Verde", cq: "35", itu: "46" },
{ p: "D6", c: "Comoros", cq: "39", itu: "53" },
{ p: "DA-DM, Y", c: "Germany", cq: "14", itu: "28" },
{ p: "DU, DZ", c: "Philippines", cq: "27", itu: "50" },
{ p: "E3", c: "Erythrea", cq: "37", itu: "48" },
{ p: "E4", c: "Palestina", cq: "20", itu: "39" },
{ p: "EA-EH", c: "Spain", cq: "14", itu: "37" },
{ p: "EA6-EH6", c: "Balearic Isl.", cq: "14", itu: "37" },
{ p: "EA8-EH8", c: "Canary Isl.", cq: "33", itu: "36" },
{ p: "EA9-EH9", c: "Ceuta & Melilla", cq: "33", itu: "37" },
{ p: "EI, EJ", c: "Ireland", cq: "14", itu: "27" },
{ p: "EK", c: "Armenia", cq: "21", itu: "29" },
{ p: "EL", c: "Liberia", cq: "35", itu: "46" },
{ p: "EP, EQ", c: "Iran", cq: "21", itu: "40" },
{ p: "ER", c: "Moldova", cq: "16", itu: "29" },
{ p: "ES", c: "Estonia", cq: "15", itu: "29" },
{ p: "ET", c: "Ethiopia", cq: "37", itu: "48" },
{ p: "EU-EW", c: "Belarus", cq: "16", itu: "29" },
{ p: "EX", c: "Kyrgystan", cq: "17", itu: "30,31" },
{ p: "EY", c: "Tajikistan", cq: "17", itu: "30" },
{ p: "EZ", c: "Turkmenistan", cq: "17", itu: "30" },
{ p: "FA-FF, TM", c: "France", cq: "14", itu: "27" },
{ p: "FG", c: "Guadeloupe", cq: "08", itu: "11" },
{ p: "FH", c: "Mayotte", cq: "39", itu: "53" },
{ p: "FJ, FS", c: "French St. Martin", cq: "08", itu: "11" },
{ p: "FK", c: "New Caledonia", cq: "32", itu: "56" },
{ p: "FM", c: "Martinique", cq: "08", itu: "11" },
{ p: "FO", c: "French Polynesia", cq: "32", itu: "63" },
{ p: "FO0", c: "Clipperton Isl.", cq: "07", itu: "10" },
{ p: "FO0", c: "Marquesas", cq: "31", itu: "63" },
{ p: "FO0", c: "Austral Isl.", cq: "32", itu: "63" },
{ p: "FP", c: "St. Pierre & Miquelon", cq: "05", itu: "09" },
{ p: "FR", c: "Reunion", cq: "39", itu: "53" },
{ p: "FR/J", c: "Juan de Nova", cq: "39", itu: "53" },
{ p: "FR/G", c: "Glorioso", cq: "39", itu: "53" },
{ p: "FR/T", c: "Tromelin", cq: "39", itu: "53" },
{ p: "FT8W", c: "Crozet Isl.", cq: "39", itu: "68" },
{ p: "FT8X", c: "Kerguelen Isl.", cq: "39", itu: "68" },
{ p: "FT8Z", c: "Amsterdam & St. Paul Isl.", cq: "39", itu: "68" },
{ p: "FW", c: "Wallis & Futuna Isl.", cq: "32", itu: "62" },
{ p: "FY", c: "French Guiana", cq: "09", itu: "12" },
{ p: "G, GX, M", c: "England", cq: "14", itu: "27" },
{ p: "GD, GT, MD", c: "Isle of Man", cq: "14", itu: "27" },
{ p: "GI, GN, MI", c: "Northern Ireland", cq: "14", itu: "27" },
{ p: "GJ, GH, MJ", c: "Jersey", cq: "14", itu: "27" },
{ p: "GM, GS, MM", c: "Scotland", cq: "14", itu: "27" },
{ p: "GU, GP, MU", c: "Guernsey", cq: "14", itu: "27" },
{ p: "GW, GC, MW", c: "Wales", cq: "14", itu: "27" },
{ p: "H4", c: "Solomon Isl.", cq: "28", itu: "51" },
{ p: "H40", c: "Temotu Province", cq: "32", itu: "51" },
{ p: "HA, HG", c: "Hungary", cq: "14", itu: "28" },
{ p: "HB", c: "Switzerland", cq: "14", itu: "28" },
{ p: "HB0", c: "Liechtenstein", cq: "14", itu: "28" },
{ p: "HC, HD", c: "Ecuador", cq: "10", itu: "12" },
{ p: "HC8, HD8", c: "Galapagos Isl.", cq: "10", itu: "12" },
{ p: "HH", c: "Haiti", cq: "08", itu: "11" },
{ p: "HI", c: "Dominican Rep.", cq: "08", itu: "11" },
{ p: "HK, HJ", c: "Colombia", cq: "09", itu: "12" },
{ p: "HK0M", c: "Malpelo Isl.", cq: "09", itu: "12" },
{ p: "HK0S", c: "San Andres & Providencia", cq: "07", itu: "11" },
{ p: "HL, HM, DS", c: "South Korea", cq: "25", itu: "44" },
{ p: "HP, HO, 3E", c: "Panama", cq: "07", itu: "11" },
{ p: "HR, HQ", c: "Honduras", cq: "07", itu: "11" },
{ p: "HS, E2", c: "Thailand", cq: "26", itu: "49" },
{ p: "HV", c: "Vatican", cq: "15", itu: "28" },
{ p: "HZ, 7Z", c: "Saudi Arabia", cq: "21", itu: "39" },
{ p: "I, IA-IZ", c: "Italy", cq: "15,33", itu: "28,37" },
{ p: "IS0, IM0", c: "Sardinia", cq: "15", itu: "28" },
{ p: "J2", c: "Djibouti", cq: "37", itu: "48" },
{ p: "J3", c: "Grenada", cq: "08", itu: "11" },
{ p: "J5", c: "Guinea Bissau", cq: "35", itu: "46" },
{ p: "J6", c: "St. Lucia", cq: "08", itu: "11" },
{ p: "J7", c: "Dominica", cq: "08", itu: "11" },
{ p: "J8", c: "St. Vincent", cq: "08", itu: "11" },
{ p: "JA-JS", c: "Japan", cq: "25", itu: "45" },
{ p: "JD1M", c: "Minami Torishima", cq: "27", itu: "90" },
{ p: "JD1O", c: "Ogasawara", cq: "27", itu: "45" },
{ p: "JT, JV", c: "Mongolia", cq: "23", itu: "32" },
{ p: "JW", c: "Svalbard Isl.", cq: "40", itu: "18" },
{ p: "JX", c: "Jan Mayen Isl.", cq: "40", itu: "18" },
{ p: "JY", c: "Jordan", cq: "20", itu: "39" },
{ p: "K, W, N, AA-AK", c: "USA", cq: "3,4,5", itu: "6,7,8" },
{ p: "T8, KC6", c: "West Caroline Isl. Belau", cq: "27", itu: "64" },
{ p: "KG4", c: "Guantanamo Bay", cq: "08", itu: "11" },
{ p: "KH1", c: "Baker & Howland Isl.", cq: "31", itu: "61" },
{ p: "KH2", c: "Guam", cq: "27", itu: "64" },
{ p: "KH3", c: "Johnston Isl.", cq: "31", itu: "61" },
{ p: "KH4", c: "Midway Isl.", cq: "31", itu: "61" },
{ p: "KH5", c: "Palmyra & Jarvis Isl.", cq: "31", itu: "61,62" },
{ p: "KH5K", c: "Kingman Reef", cq: "31", itu: "61" },
{ p: "KH6, KH7", c: "Hawaii Isl.", cq: "31", itu: "61" },
{ p: "KH7K", c: "Kure Isl.", cq: "31", itu: "61" },
{ p: "KH8", c: "American Samoa", cq: "32", itu: "62" },
{ p: "KH9", c: "Wake Isl.", cq: "31", itu: "65" },
{ p: "KH0", c: "Mariana Isl.", cq: "27", itu: "64" },
{ p: "KL7", c: "Alaska", cq: "01", itu: "01,02" },
{ p: "KP1", c: "Navassa Isl.", cq: "08", itu: "11" },
{ p: "KP2", c: "Virgin Isl.", cq: "08", itu: "11" },
{ p: "KP3, KP4", c: "Puerto Rico", cq: "08", itu: "11" },
{ p: "KP5", c: "Desecheo Isl.", cq: "08", itu: "11" },
{ p: "LA, LN", c: "Norway", cq: "14", itu: "18" },
{ p: "L, LU, LW", c: "Argentina", cq: "13", itu: "14,15,16" },
{ p: "LX", c: "Luxembourg", cq: "14", itu: "27" },
{ p: "LY", c: "Lithuania", cq: "15", itu: "29" },
{ p: "LZ", c: "Bulgaria", cq: "20", itu: "28" },
{ p: "OA, OC", c: "Peru", cq: "10", itu: "12" },
{ p: "OD", c: "Lebanon", cq: "20", itu: "39" },
{ p: "OE", c: "Austria", cq: "15", itu: "28" },
{ p: "OG, OH, OI", c: "Finland", cq: "15", itu: "18" },
{ p: "OH0", c: "Aland Isl.", cq: "15", itu: "18" },
{ p: "OJ0, OH0M", c: "Market Reef", cq: "15", itu: "18" },
{ p: "OK, OL", c: "Czech Republic", cq: "15", itu: "28" },
{ p: "OM", c: "Slovak Republic", cq: "15", itu: "28" },
{ p: "ON-OT", c: "Belgium", cq: "14", itu: "27" },
{ p: "OX", c: "Greenland", cq: "40", itu: "05,75" },
{ p: "OY", c: "Faroe Isl.", cq: "14", itu: "18" },
{ p: "OZ", c: "Denmark", cq: "14", itu: "28" },
{ p: "P2", c: "Papua New Guinea", cq: "28", itu: "51" },
{ p: "P4", c: "Aruba", cq: "09", itu: "11" },
{ p: "P5", c: "North Korea", cq: "25", itu: "44" },
{ p: "PA-PI", c: "The Netherlands", cq: "14", itu: "27" },
{ p: "PJ2,4,9", c: "Bonaire, Curacao", cq: "09", itu: "11" },
{ p: "PJ7,5,8", c: "St. Maarten, Saba", cq: "08", itu: "11" },
{ p: "PP-PY", c: "Brazil", cq: "11", itu: "12,13,14,15" },
{ p: "PP0, PY0F", c: "Fernando de Noronha", cq: "11", itu: "13" },
{ p: "PP0, PY0S", c: "St. Peter & Paul's Rocks", cq: "11", itu: "13" },
{ p: "PP0, PY0T", c: "Trindade & Martim Vaz", cq: "11", itu: "15" },
{ p: "PZ", c: "Surinam", cq: "09", itu: "12" },
{ p: "R1FJ", c: "Franz Josef Land", cq: "40", itu: "75" },
{ p: "R1MV", c: "Malyj Vysotskij Isl.", cq: "16", itu: "29" },
{ p: "S2", c: "Bangladesh", cq: "22", itu: "41" },
{ p: "S5", c: "Slovenia", cq: "15", itu: "28" },
{ p: "S7", c: "Seychelles", cq: "39", itu: "53" },
{ p: "S9", c: "Sao Tome & Principe", cq: "36", itu: "47" },
{ p: "S0", c: "Western Sahara", cq: "33", itu: "46" },
{ p: "SA-SM", c: "Sweden", cq: "14", itu: "18" },
{ p: "SN-SR, 3Z", c: "Poland", cq: "15", itu: "28" },
{ p: "ST", c: "Sudan", cq: "34", itu: "48" },
{ p: "SU", c: "Egypt", cq: "34", itu: "38" },
{ p: "SV, SZ, J4", c: "Greece", cq: "20", itu: "28" },
{ p: "SV5, J45", c: "Dodecanese", cq: "20", itu: "28" },
{ p: "SV9, J49", c: "Crete", cq: "20", itu: "28" },
{ p: "SV2A, SY", c: "Mount Athos", cq: "20", itu: "28" },
{ p: "T2", c: "Tuvalu", cq: "31", itu: "65" },
{ p: "T30", c: "West Kiribati", cq: "31", itu: "65" },
{ p: "T31", c: "Cent. Kiribati", cq: "31", itu: "62" },
{ p: "T32", c: "East Kiribati", cq: "31", itu: "61,62,63" },
{ p: "T33", c: "Banaba Isl.", cq: "31", itu: "65" },
{ p: "T5, 6O", c: "Somalia", cq: "37", itu: "48" },
{ p: "T7", c: "San Marino", cq: "15", itu: "28" },
{ p: "T9", c: "Bosnia - Herzegovina", cq: "15", itu: "28" },
{ p: "TA-TC", c: "Turkey", cq: "20", itu: "39" },
{ p: "TF", c: "Iceland", cq: "40", itu: "17" },
{ p: "TG, TD", c: "Guatemala", cq: "07", itu: "11" },
{ p: "TI, TE", c: "Costa Rica", cq: "07", itu: "11" },
{ p: "TI9", c: "Cocos Isl.", cq: "07", itu: "11" },
{ p: "TJ", c: "Cameroon", cq: "36", itu: "47" },
{ p: "TK", c: "Corsica", cq: "15", itu: "28" },
{ p: "TL", c: "Centr. African Rep.", cq: "36", itu: "47" },
{ p: "TN", c: "Congo", cq: "36", itu: "52" },
{ p: "TR", c: "Gabon", cq: "36", itu: "52" },
{ p: "TT", c: "Chad", cq: "36", itu: "47" },
{ p: "TU", c: "Ivory Coast", cq: "35", itu: "46" },
{ p: "TY", c: "Benin", cq: "35", itu: "46" },
{ p: "TX", c: "Chesterfield Islands", cq: "39", itu: "53" },
{ p: "TZ", c: "Mali", cq: "35", itu: "46" },
{ p: "UA-RZ (Eur)", c: "European Russia", cq: "16", itu: "19,29,30" },
{ p: "UA2, RW2", c: "Kaliningrad", cq: "15", itu: "29" },
{ p: "UA-RZ (Asi)", c: "Asiatic Russia", cq: "16-19", itu: "21,27,30,33" },
{ p: "UJ-UM", c: "Uzbekistan", cq: "17", itu: "30" },
{ p: "UN-UQ", c: "Kazakhstan", cq: "17", itu: "29,30,31" },
{ p: "UR-EM", c: "Ukraine", cq: "16", itu: "29" },
{ p: "V2", c: "Antigua & Barbuda", cq: "08", itu: "11" },
{ p: "V3", c: "Belize", cq: "07", itu: "11" },
{ p: "V4", c: "St. Kits, Nevis", cq: "08", itu: "11" },
{ p: "V5", c: "Namibia", cq: "38", itu: "57" },
{ p: "V6", c: "Micronesia", cq: "27", itu: "65" },
{ p: "V7", c: "Marshall Isl.", cq: "31", itu: "65" },
{ p: "V8", c: "Brunei", cq: "28", itu: "54" },
{ p: "VE, VC, VO", c: "Canada", cq: "01-05", itu: "02-09" },
{ p: "VK", c: "Australia", cq: "29,30", itu: "55,58,59" },
{ p: "VK9C", c: "Cocos Keeling Isl.", cq: "29", itu: "54" },
{ p: "VK9L", c: "Lord Howe Isl.", cq: "30", itu: "60" },
{ p: "VK9M", c: "Mellish Reef", cq: "30", itu: "56" },
{ p: "VK9N", c: "Norfolk Isl.", cq: "32", itu: "60" },
{ p: "VK9W", c: "Willis Isl.", cq: "30", itu: "55" },
{ p: "VK9X", c: "Christmas Isl.", cq: "29", itu: "54" },
{ p: "VK0", c: "Heard Isl.", cq: "39", itu: "68" },
{ p: "VK0", c: "Macquarie Isl.", cq: "30", itu: "60" },
{ p: "VP2E", c: "Anguilla", cq: "08", itu: "11" },
{ p: "VP2M", c: "Montserrat", cq: "08", itu: "11" },
{ p: "VP2V", c: "Brit. Virgin Isl.", cq: "08", itu: "11" },
{ p: "VP5", c: "Turks & Caicos Isl.", cq: "08", itu: "11" },
{ p: "VP6", c: "Pitcairn Isl.", cq: "32", itu: "63" },
{ p: "VP8", c: "Falkland Isl.", cq: "13", itu: "16" },
{ p: "VP8, LU", c: "South Georgia", cq: "13", itu: "73" },
{ p: "VP8, LU", c: "South Orkney", cq: "13", itu: "73" },
{ p: "VP8, LU", c: "South Shetland", cq: "13", itu: "73" },
{ p: "VP9", c: "Bermuda", cq: "05", itu: "11" },
{ p: "VQ9", c: "Chagos", cq: "39", itu: "41" },
{ p: "VR2", c: "Hong Kong", cq: "24", itu: "44" },
{ p: "VU", c: "India", cq: "22", itu: "41" },
{ p: "VU4", c: "Andaman & Nicobar", cq: "26", itu: "49" },
{ p: "VU7", c: "Laccadive Isl.", cq: "22", itu: "41" },
{ p: "XA-XI", c: "Mexico", cq: "06", itu: "10" },
{ p: "XT", c: "Burkino Fasso", cq: "35", itu: "46" },
{ p: "XU", c: "Kampuchea", cq: "26", itu: "49" },
{ p: "XW", c: "Laos", cq: "26", itu: "49" },
{ p: "XX9", c: "Macao", cq: "24", itu: "44" },
{ p: "XZ, XY", c: "Myanmar", cq: "26", itu: "49" },
{ p: "YA", c: "Afghanistan", cq: "21", itu: "40" },
{ p: "YB-YH", c: "Indonesia", cq: "28", itu: "51-54" },
{ p: "YI", c: "Iraq", cq: "21", itu: "39" },
{ p: "YJ", c: "Vanuatu", cq: "32", itu: "56" },
{ p: "YK", c: "Syria", cq: "20", itu: "39" },
{ p: "YL", c: "Latvia", cq: "15", itu: "29" },
{ p: "YN", c: "Nicaragua", cq: "07", itu: "11" },
{ p: "YO-YR", c: "Romania", cq: "20", itu: "28" },
{ p: "YS", c: "El Salvador", cq: "07", itu: "11" },
{ p: "YU-4O", c: "Yugoslavia (former)", cq: "15", itu: "28" },
{ p: "YV-YY", c: "Venezuela", cq: "09", itu: "12" },
{ p: "YV0", c: "Aves Isl.", cq: "08", itu: "11" },
{ p: "Z2", c: "Zimbabwe", cq: "38", itu: "53" },
{ p: "Z3", c: "Macedonia", cq: "15", itu: "28" },
{ p: "ZA", c: "Albania", cq: "15", itu: "28" },
{ p: "ZB2", c: "Gibraltar", cq: "14", itu: "37" },
{ p: "ZC4", c: "Cyprus (UK Base)", cq: "20", itu: "39" },
{ p: "ZD7", c: "St. Helena", cq: "36", itu: "66" },
{ p: "ZD8", c: "Ascension Isl.", cq: "36", itu: "66" },
{ p: "ZD9", c: "Tristan Da Cunha", cq: "38", itu: "66" },
{ p: "ZF", c: "Cayman Isl.", cq: "08", itu: "11" },
{ p: "ZK", c: "Cook Isl.", cq: "32", itu: "62" },
{ p: "ZL, ZM", c: "New Zealand", cq: "32", itu: "60" },
{ p: "ZP", c: "Paraguay", cq: "11", itu: "14" },
{ p: "ZR-ZU", c: "South Africa", cq: "38", itu: "57" },
{ p: "1A", c: "Order of Malta", cq: "15", itu: "28" },
{ p: "1S, 9M0", c: "Spratly Isl.", cq: "26", itu: "50" },
{ p: "3A", c: "Monaco", cq: "14", itu: "27" },
{ p: "3B6-7", c: "Agalega", cq: "39", itu: "53" },
{ p: "3B8", c: "Mauritius", cq: "39", itu: "53" },
{ p: "3B9", c: "Rodrigues Isl.", cq: "39", itu: "53" },
{ p: "3C", c: "Equatorial Guinea", cq: "36", itu: "47" },
{ p: "3C0", c: "Annobon Isl.", cq: "36", itu: "52" },
{ p: "3D2", c: "Fiji Isl.", cq: "32", itu: "56" },
{ p: "3DA-3D6", c: "Swaziland", cq: "38", itu: "57" },
{ p: "3V", c: "Tunisia", cq: "33", itu: "37" },
{ p: "3W, XV", c: "Vietnam", cq: "26", itu: "49" },
{ p: "3X", c: "Guinea", cq: "35", itu: "46" },
{ p: "3Y5", c: "Bouvet", cq: "38", itu: "67" },
{ p: "3Y0", c: "Peter 1 Isl.", cq: "12", itu: "72" },
{ p: "4K, 4J", c: "Azerbaidjan", cq: "21", itu: "29" },
{ p: "4L", c: "Georgia", cq: "21", itu: "29" },
{ p: "4S", c: "Sri Lanka", cq: "22", itu: "41" },
{ p: "4U1ITU", c: "ITU Geneva", cq: "14", itu: "28" },
{ p: "4U1UN", c: "UN HQ NY", cq: "05", itu: "08" },
{ p: "4W", c: "East Timor", cq: "28", itu: "54" },
{ p: "4X, 4Z", c: "Israel", cq: "20", itu: "39" },
{ p: "5A", c: "Libya", cq: "34", itu: "38" },
{ p: "5B, C4", c: "Cyprus", cq: "20", itu: "39" },
{ p: "5H, 5I", c: "Tanzania", cq: "37", itu: "53" },
{ p: "5N, 5O", c: "Nigeria", cq: "35", itu: "46" },
{ p: "5R, 5S", c: "Madagascar", cq: "39", itu: "53" },
{ p: "5T", c: "Mauritania", cq: "35", itu: "46" },
{ p: "5U", c: "Niger", cq: "35", itu: "46" },
{ p: "5V", c: "Togo", cq: "35", itu: "46" },
{ p: "5W", c: "Western Samoa", cq: "32", itu: "62" },
{ p: "5X", c: "Uganda", cq: "37", itu: "48" },
{ p: "5Y, 5Z", c: "Kenya", cq: "37", itu: "48" },
{ p: "6V, 6W", c: "Senegal", cq: "35", itu: "46" },
{ p: "6Y", c: "Jamaica", cq: "08", itu: "11" },
{ p: "7O", c: "Yemen", cq: "21", itu: "39" },
{ p: "7P", c: "Lesotho", cq: "38", itu: "57" },
{ p: "7Q", c: "Malawi", cq: "37", itu: "53" },
{ p: "7T-7Y", c: "Algeria", cq: "33", itu: "37" },
{ p: "8P", c: "Barbados", cq: "08", itu: "11" },
{ p: "8Q", c: "Maldives", cq: "22", itu: "41" },
{ p: "8R", c: "Guyana", cq: "09", itu: "12" },
{ p: "9A", c: "Croatia", cq: "15", itu: "28" },
{ p: "9G", c: "Ghana", cq: "35", itu: "46" },
{ p: "9H", c: "Malta", cq: "15", itu: "28" },
{ p: "9J, 9I", c: "Zambia", cq: "36", itu: "53" },
{ p: "9K", c: "Kuwait", cq: "21", itu: "39" },
{ p: "9L", c: "Sierra Leone", cq: "35", itu: "46" },
{ p: "9M", c: "Malaysia", cq: "28", itu: "54" },
{ p: "9N", c: "Nepal", cq: "22", itu: "42" },
{ p: "9Q, 9T", c: "Rep. of Congo", cq: "36", itu: "52" },
{ p: "9U", c: "Burundi", cq: "36", itu: "52" },
{ p: "9V", c: "Singapore", cq: "28", itu: "54" },
{ p: "9X", c: "Rwanda", cq: "36", itu: "52" },
{ p: "9Y, 9Z", c: "Trinidad & Tobago", cq: "09", itu: "11" }

        ];


        const qCodes = [
        { k: "QAM", p: "Zadnji meteorološki podatki." },
        { k: "QAP", p: "Poslušaj me na… (kHz, MHz). Ostani na frekvenci." },
        { k: "QAR", p: "Zapuščam frekvenco." },
        { k: "QAV", p: "Pozivam, kličem." },
        { k: "QAZ", p: "Pripravljam se za delo v neurju (izključujem postajo)." },
        { k: "QBF", p: "V tekmovanju sva že imela zvezo." },
        { k: "QBT", p: "Pri telegrafiranju ti izpadajo pike." },
        { k: "QCM", p: "V tvoji oddaji so napake." },
        { k: "QDH", p: "Zdajšnje motnje prihajajo od…" },
        { k: "QHF", p: "Pridem na Ham fest." },
        { k: "QIF", p: "Na frekvenci… dela postaja… (poz. znak)." },
        { k: "QLF", p: "Ali delaš z levo nogo? (Zelo žaljivo!)" },
        { k: "QLZ", p: "Zelo sem len (ali: si len)." },
        { k: "QMT", p: "Sporočilo pošljem po pošti." },
        { k: "QRA", p: "Ime moje postaje je…" },
        { k: "QRAR", p: "Moj naslov v Call book-u je točen." },
        { k: "QRB", p: "Razdalja med najinima postajama je…" },
        { k: "QRG", p: "Točna frekvenca (moja) je… (kHz, MHz)." },
        { k: "QRH", p: "Tvoja frekvenca niha." },
        { k: "QRI", p: "Ton tvoje oddaje je: 1-dober, 2-spremenljiv, 3-slab." },
        { k: "QRJ", p: "Signali so slabi." },
        { k: "QRK", p: "Razumljivost: 1-zanič do 5-odlična." },
        { k: "QRL", p: "Zaseden sem. Prosim, ne moti." },
        { k: "QRM", p: "Imam motnje (druge postaje): 1 do 5." },
        { k: "QRN", p: "Moti me statika (vreme): 1 do 5." },
        { k: "QRNN", p: "Motnje od električnih naprav." },
        { k: "QRO", p: "Povečaj oddajno moč. Postaja z veliko močjo." },
        { k: "QRP", p: "Zmanjšaj oddajno moč (do 10 W)." },
        { k: "QRPP", p: "Postaja zelo male moči (do 1 W)." },
        { k: "QRR", p: "Pripravljen sem na avtomatično delo." },
        { k: "QRRR", p: "Klic v sili. Sledi nujni poziv." },
        { k: "QRQ", p: "Oddajaj (tipkaj) hitreje." },
        { k: "QRS", p: "Oddajaj (tipkaj) počasneje." },
        { k: "QRSS", p: "Oddaja zelo počasne telegrafije." },
        { k: "QRT", p: "Preneham oddajati." },
        { k: "QRU", p: "Nič nimam več za povedati." },
        { k: "QRV", p: "Pripravljen sem. Sem aktiven." },
        { k: "QRW", p: "Prosim obvesti…, da ga kličem na… (kHz)." },
        { k: "QRX", p: "Na kratko prekinjam. Ponovno te pokličem čez… (min)." },
        { k: "QRY", p: "Na vrsti si za zvezo pod zaporedno št. …" },
        { k: "QRZ", p: "Kličem. Kliče te… (poz znak) na… (kHz)." },
        { k: "QQQ", p: "Prekinjam oddajo, pojasnilo sledi kasneje." },
        { k: "QSA", p: "Moč signala: 1 do 5." },
        { k: "QSB", p: "Tvoj signal niha. (Feding)." },
        { k: "QSD", p: "Delaš napake v tipkanju." },
        { k: "QSI", p: "Ne morem se vključiti v zvezo z…" },
        { k: "QSK", p: "Slišim te med mojo oddajo. Soglašam z BK načinom." },
        { k: "QSL", p: "Potrjujem sprejem (QSL kartica)." },
        { k: "QSLL", p: "Zamenjala si bova QSL kartici." },
        { k: "QSN", p: "Slišal sem te na… (kHz)." },
        { k: "QSO", p: "Zveza. Lahko komuniciram z…." },
        { k: "QSP", p: "Posredoval bom do…." },
        { k: "QSR", p: "Ponovi poziv na pozivni frekvenci." },
        { k: "QSS", p: "Za delo bom uporabljal frekvenco… (kHz)." },
        { k: "QST", p: "Sporočilo vsem brez odgovora." },
        { k: "QSU", p: "Pokliči me na… (kHz) ob… (uri)." },
        { k: "QSUF", p: "Pokliči me po telefonu." },
        { k: "QSV", p: "Pošiljaj serijo V-jev na tej frekvenci." },
        { k: "QSW", p: "Prehajam na frekvenco… (kHz)." },
        { k: "QSX", p: "Poslušal bom… na… (kHz)." },
        { k: "QSY", p: "Spremenil bom frekvenco na… (kHz)." },
        { k: "QSZ", p: "Tipkaj vsako besedo dvakrat." },
        { k: "QTA", p: "Preklicujem (aktivnost)." },
        { k: "QTC", p: "Imam sporočilo zate." },
        { k: "QTH", p: "Moja lokacija (naslov) je…" },
        { k: "QTR", p: "Točen čas je…" },
        { k: "QTQ", p: "Uporabljam (bom) mednarodno kodo." },
        { k: "QTU", p: "Moja postaja je aktivna od… do… (ure)." },
        { k: "QTV", p: "Čakaj me na frekvenci… (kHz)." },
        { k: "QTS", p: "Ponavljam pozivni znak." },
        { k: "QTX", p: "Čakal te bom do nadalnjega." },
        { k: "QUA", p: "Imam novico od…." },
        { k: "QUD", p: "Sprejel sem nujen signal." },
        { k: "QUF", p: "Sprejel sem klic v sili." },
        { k: "QUM", p: "Nadaljujem z normalnim delom." }
    ];

    const alphabet = {
            'a': { slo: 'ANKARAN', int: 'ALPHA' },
            'b': { slo: 'BLED', int: 'BRAVO' },
            'c': { slo: 'CELJE', int: 'CHARLIE' },
            'č': { slo: 'ČATEŽ', int: '/' },
            'd': { slo: 'DRAVA', int: 'DELTA' },
            'e': { slo: 'EUROPA', int: 'ECHO' },
            'f': { slo: 'FALA', int: 'FOXTROT' },
            'g': { slo: 'GORICA', int: 'GOLF' },
            'h': { slo: 'HRASTNIK', int: 'HOTEL' },
            'i': { slo: 'IZOLA', int: 'INDIA' },
            'j': { slo: 'JADRAN', int: 'JULIET' },
            'k': { slo: 'KAMNIK', int: 'KILO' },
            'l': { slo: 'LJUBLJANA', int: 'LIMA' },
            'm': { slo: 'MARIBOR', int: 'MIKE' },
            'n': { slo: 'NANOS', int: 'NOVEMBER' },
            'o': { slo: 'ORMOŽ', int: 'OSCAR' },
            'p': { slo: 'PIRAN', int: 'PAPA' },
            'q': { slo: 'QUEEN', int: 'QUEBEC' },
            'r': { slo: 'RAVNE', int: 'ROMEO' },
            's': { slo: 'SOČA', int: 'SIERRA' },
            'š': { slo: 'ŠMARJE', int: '/' },
            't': { slo: 'TRIGLAV', int: 'TANGO' },
            'u': { slo: 'UNEC', int: 'UNIFORM' },
            'v': { slo: 'VELENJE', int: 'VICTOR' },
            'w': { slo: 'DVOJNI V', int: 'WHISKEY' },
            'x': { slo: 'IKS', int: 'X-RAY' },
            'y': { slo: 'IPSILON', int: 'YANKEE' },
            'z': { slo: 'ZALOG', int: 'ZULU' },
            'ž': { slo: 'ŽALEC', int: '/' }
        };